# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 21:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("account_admin", "Account Administrator"),
                    ("manager", "Manager"),
                ],
                default="account_admin",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
