# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 18:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_auto_20160720_1440"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="role",
            field=models.CharField(
                choices=[("manager", "Manager"), ("examiner", "Medical Examiner")],
                default="manager",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="facilityuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("account_admin", "Account Administrator"),
                    ("manager", "Manager"),
                    ("examiner", "Medical Examiner"),
                ],
                max_length=255,
            ),
        ),
    ]
