# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 20:02


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0023_archived1823"),
        ("facilities", "0004_auto_20170216_1823"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInviteResidentAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resident_accesses",
                        to="facilities.UserInvite",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_invites",
                        to="residents.Resident",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "invite resident accesses",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userinviteresidentaccess",
            unique_together=set([("invite", "resident")]),
        ),
    ]
