# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-23 23:36


import django.db.models.deletion
from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0085_fix_employees_with_invalid_responsibility_questions"),
        ("facilities", "0005_auto_20170320_2002"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signed_on", models.DateTimeField(auto_now=True)),
                (
                    "pdf",
                    models.FileField(
                        upload_to=apps.base.models.random_name_in("facilities/business-agreements")
                    ),
                ),
                (
                    "facility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainings.Facility",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facilities.FacilityUser",
                    ),
                ),
            ],
        ),
    ]
