# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-28 19:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0006_businessagreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("account_admin", "Account Administrator"),
                    ("manager", "Manager"),
                    ("examiner", "Medical Examiner"),
                    ("app_user", "App User"),
                ],
                max_length=255,
            ),
        ),
    ]
