# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-09 01:14


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timed_auth_token", "0001_initial"),
        ("facilities", "0007_auto_20190228_1913"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomTimedAuthToken",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("timed_auth_token.timedauthtoken",),
        ),
    ]
