# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-29 06:17


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0116_facility_is_lms_module_enabled"),
        ("facilities", "0008_customtimedauthtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="trainings.Employee",
            ),
        ),
    ]
