# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-29 18:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0010_auto_20190719_1527"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityuser",
            name="can_see_residents",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="facilityuser",
            name="can_see_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userinvite",
            name="can_see_residents",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userinvite",
            name="can_see_staff",
            field=models.BooleanField(default=True),
        ),
    ]
