# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-12-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0011_auto_20190729_1840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("account_admin", "Account Administrator"),
                    ("manager", "Manager"),
                    ("examiner", "Medical Examiner"),
                    ("trainings_user", "Trainings User"),
                ],
                max_length=255,
            ),
        ),
    ]
