# -*- coding: utf-8 -*-
# Generated by Django 1.9.7on 2020-12-04 9:33
from __future__ import unicode_literals

from django.db import migrations


def move_facility_user_roles(apps, schema_editor):
    FacilityUser = apps.get_model("facilities", "FacilityUser")

    for facility_user in FacilityUser.objects.all():
        if facility_user.role == "app_user":
            facility_user.role = "trainings_user"
        facility_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0012_auto_20201204_1218"),
    ]

    operations = [migrations.RunPython(move_facility_user_roles, migrations.RunPython.noop)]
