# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-12-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0013_move_facility_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="phone_number",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="userinvite",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("examiner", "Medical Examiner"),
                    ("trainings_user", "Trainings User"),
                ],
                max_length=255,
            ),
        ),
    ]
