# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-02-12 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0014_auto_20201214_1331"),
    ]

    operations = [
        migrations.RenameModel("CustomTimedAuthToken", "TrainingsTimedAuthToken"),
    ]
