# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 13:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0074_auto_20160520_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="primary_administrator_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
