# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 14:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0075_facility_primary_administrator_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="subdomain",
        ),
    ]
