# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 14:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0076_remove_facility_subdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="license_number",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
