# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 15:24


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0077_facility_license_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainings.TaskType",
                    ),
                ),
            ],
        ),
    ]
