# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 15:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0078_globalrequirement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktype",
            name="required_for",
            field=models.ManyToManyField(blank=True, to="trainings.Responsibility"),
        ),
    ]
