# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 20:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0079_auto_20160614_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="deactivation_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="responsibility",
            name="question",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="rule",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="trainingevent",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
