# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 15:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0080_auto_20160615_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
