# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 17:56


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0081_facility_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsibility",
            name="question_position_restriction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trainings.Position",
            ),
        ),
    ]
