# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 17:46


from django.db import migrations


def forward(apps, schema_editor):
    Employee = apps.get_model("trainings", "Employee")
    FacilityUser = apps.get_model("facilities", "FacilityUser")

    for employee in Employee.objects.exclude(user=None):
        facility = employee.facility
        user = employee.user
        user.first_name = employee.first_name
        user.last_name = employee.last_name
        user.save()
        FacilityUser.objects.create(facility=facility, user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0082_responsibility_question_position_restriction"),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
