# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 17:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0083_move_user_from_employee_to_facility_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
    ]
