# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 17:19


from django.db import migrations


def forward(apps, schema_editor):
    Responsibility = apps.get_model("trainings", "Responsibility")
    Employee = apps.get_model("trainings", "Employee")

    restricted_questions = Responsibility.objects.exclude(
        question_position_restriction__isnull=True
    )
    for responsibility in restricted_questions:
        invalid_employees = Employee.objects.filter(other_responsibilities=responsibility).exclude(
            positions=responsibility.question_position_restriction
        )
        for employee in invalid_employees:
            employee.other_responsibilities.remove(responsibility)
            employee.trainings_task_set.filter(type__required_for=responsibility).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0084_remove_employee_user"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
