# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-03 13:52


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alfdirectory", "0002_auto_20160630_1141"),
        ("trainings", "0085_fix_employees_with_invalid_responsibility_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="directory_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="alfdirectory.Facility",
            ),
        ),
    ]
