# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-03 13:53


from django.db import migrations


def set_directory_facility(apps, schema_editor):
    Facility = apps.get_model("trainings", "Facility")
    DirectoryFacility = apps.get_model("alfdirectory", "Facility")
    for facility in Facility.objects.all():
        try:
            facility.directory_facility = DirectoryFacility.objects.get(
                license_number=facility.license_number
            )
            facility.save()
        except (
            DirectoryFacility.DoesNotExist,
            DirectoryFacility.MultipleObjectsReturned,
        ):
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0086_facility_directory_facility"),
    ]

    operations = [migrations.RunPython(set_directory_facility)]
