# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-03 15:33


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0087_auto_20170803_1353"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="license_number",
        ),
    ]
