# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-04 18:13


from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0088_remove_facility_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.base.models.random_name_in("employees/employee/pictures"),
            ),
        ),
    ]
