# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-05 13:22


import django.db.models.deletion
from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0090_auto_20170929_1557"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskHistoryCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate",
                    models.FileField(upload_to=apps.base.models.random_name_in("certificates")),
                ),
                (
                    "task_history",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="trainings.TaskHistory",
                    ),
                ),
            ],
        ),
    ]
