# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 05:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0091_taskhistorycertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskhistorycertificate",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
