# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-13 02:29


import django.db.models.deletion
from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0092_taskhistorycertificate_uploaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskHistoryCertificatePage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.FileField(upload_to=apps.base.models.random_name_in("certificates")),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="trainings.TaskHistoryCertificate",
                    ),
                ),
            ],
        ),
    ]
