# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-13 02:35


from django.db import migrations


def forward(apps, schema_editor):
    TaskHistoryCertificate = apps.get_model("trainings", "TaskHistoryCertificate")
    TaskHistoryCertificatePage = apps.get_model("trainings", "TaskHistoryCertificatePage")

    for certificate in TaskHistoryCertificate.objects.all():
        TaskHistoryCertificatePage.objects.create(
            certificate=certificate, page=certificate.certificate
        )


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0093_taskhistorycertificatepage"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
