# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-13 02:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0094_auto_20171113_0235"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskhistorycertificate",
            name="certificate",
        ),
    ]
