# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-10-12 19:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0095_remove_taskhistorycertificate_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="is_resident_module_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
