# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-15 20:58


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0097_all_enable_resident_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="required_after_task_type",
            field=models.ForeignKey(
                blank=True,
                help_text="When filled out, modifies the required_within field to refer to when this task type is completed, instead of the employees hire date.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_after_self",
                to="trainings.TaskType",
            ),
        ),
    ]
