# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-26 21:40


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trainings", "0098_tasktype_required_after_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
