# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-02-28 21:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0099_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="invite_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
