# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-01 19:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0100_employee_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="code_verified",
            field=models.BooleanField(default=False),
        ),
    ]
