# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-11 17:24


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0101_employee_code_verified"),
        ("trainings", "0101_auto_20190304_2241"),
    ]

    operations = []
