# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-08 17:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0101_auto_20190304_2241"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
