# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-12 14:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0102_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="bought_ebook",
            field=models.BooleanField(default=False),
        ),
    ]
