# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-11 10:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0102_tasktype_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tasktype"),
        ),
    ]
