# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-13 10:46


from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0103_auto_20190311_1005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktype",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.base.models.random_name_in("tasktype"),
            ),
        ),
    ]
