# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-13 12:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0104_auto_20190313_1046"),
        ("trainings", "0103_facility_bought_ebook"),
    ]

    operations = []
