# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-14 13:17


from django.db import migrations

from apps.base.models import UsPhoneNumberField


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0105_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="contact_fax",
            field=UsPhoneNumberField(blank=True, default="", max_length=20),
        ),
    ]
