# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-13 12:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0106_facility_contact_fax"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="max_capacity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum required (inclusive) for Facility capacity for this Task to be required. Leave 0 if there is no maximum.",
            ),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="min_capacity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum required (inclusive) for Facility capacity for this Task to be required. Leave 0 if there is no minimum.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tasktype",
            unique_together=set([]),
        ),
    ]
