# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-22 13:57


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0107_auto_20190313_1252"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("objective", models.TextField()),
                ("published", models.BooleanField(default=False)),
                (
                    "task_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course",
                        to="trainings.TaskType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trainings.Course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseItemBoolean",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boolean",
                        to="trainings.CourseItem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseItemMultiChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CourseItemText",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="trainings.CourseItem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseItemVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="trainings.CourseItem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultiChoiceOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="courseitemmultichoice",
            name="answers",
            field=models.ManyToManyField(
                related_name="choice_answers", to="trainings.MultiChoiceOption"
            ),
        ),
        migrations.AddField(
            model_name="courseitemmultichoice",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="trainings.CourseItem",
            ),
        ),
        migrations.AddField(
            model_name="courseitemmultichoice",
            name="options",
            field=models.ManyToManyField(
                related_name="choice_options", to="trainings.MultiChoiceOption"
            ),
        ),
    ]
