# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-22 15:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0108_auto_20190322_1357"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
