# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-28 13:59


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0109_course_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseitem",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="courseitemboolean",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="courseitemmultichoice",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="courseitemtext",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="courseitemvideo",
            options={"ordering": ["order"]},
        ),
    ]
