# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-01 17:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0110_auto_20190328_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="mininum_score",
            field=models.IntegerField(default=0),
        ),
    ]
