# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-01 19:02


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0111_course_mininum_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCourse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(1, "Completed"), (0, "In Progress")], default=0),
                ),
                ("score", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("completed_time", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_courses",
                        to="trainings.Course",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="trainings.Employee",
                    ),
                ),
            ],
        ),
    ]
