# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-02 10:18


import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0112_employeecourse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeecourse",
            name="completed_time",
        ),
        migrations.RemoveField(
            model_name="employeecourse",
            name="start_time",
        ),
        migrations.AddField(
            model_name="employeecourse",
            name="completed_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="employeecourse",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2019, 4, 2, 10, 18, 7, 160638, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employeecourse",
            name="status",
            field=models.IntegerField(choices=[(0, "In Progress"), (1, "Completed")], default=0),
        ),
    ]
