# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-03 09:37


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0113_auto_20190402_1018"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="mininum_score",
            new_name="minimum_score",
        ),
    ]
