# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-23 14:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0115_auto_20190404_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="is_lms_module_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
