# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-29 14:42


from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0116_facility_is_lms_module_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.base.models.random_name_in("trainings/course-item-images"),
            ),
        ),
    ]
