# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-05-29 20:59


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0117_courseitem_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeCourseItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                (
                    "course_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_course_items",
                        to="trainings.CourseItem",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_items",
                        to="trainings.Employee",
                    ),
                ),
            ],
        ),
    ]
