# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-07 17:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0118_employeecourseitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="hide_in_lms",
            field=models.BooleanField(default=False),
        ),
    ]
