# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-23 19:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0119_tasktype_hide_in_lms"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseitemvideo",
            name="embedded_url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
