# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-24 17:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0120_courseitemvideo_embedded_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseitemvideo",
            name="embedded_url",
            field=models.TextField(),
        ),
    ]
