# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-01 12:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0121_auto_20190724_1752"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="npi",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
