# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-02 18:46


from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0122_facility_npi"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseitemvideo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.base.models.random_name_in("trainings/course-item-video-thumbnail"),
            ),
        ),
    ]
