# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-20 20:19


import django.db.models.deletion
from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0123_courseitemvideo_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseItemLetterSizeImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.base.models.random_name_in(
                            "trainings/course-letter-size-images"
                        ),
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letter_size_image",
                        to="trainings.CourseItem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
