# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-04 12:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0125_course_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="fcc_signup",
            field=models.BooleanField(default=False),
        ),
    ]
