# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-05 17:01


import django.utils.timezone
from django.db import migrations

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0126_facility_fcc_signup"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
