# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-12 21:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0127_auto_20190905_1701"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="is_staff_module_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
