# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-10-24 22:03


from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0128_facility_is_staff_module_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="statement_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeecourse",
            name="signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.base.models.random_name_in("trainings/signatures"),
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(verbose_name="agenda"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="is_staff_module_enabled",
            field=models.BooleanField(
                default=True, help_text="This just hides the module in the FE"
            ),
        ),
    ]
