# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-10-25 17:31


from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0129_auto_20191024_2203"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="admin_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.base.models.random_name_in(
                    "residents/administrator-or-designee-signatures"
                ),
            ),
        ),
    ]
