# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-08 23:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0130_facility_admin_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseitem",
            name="min_duration",
            field=models.SmallIntegerField(
                blank=True,
                help_text="In seconds. Leave blank to populate with the default. Note that for videos there is no default",
                null=True,
            ),
        ),
    ]
