# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-25 09:22


from django.db import migrations


def set_lms_module_enabled(apps, schema_editor):
    Facilities = apps.get_model("trainings", "Facility")
    Facilities.objects.all().update(is_lms_module_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0131_courseitem_min_duration"),
    ]

    operations = [migrations.RunPython(set_lms_module_enabled, migrations.RunPython.noop)]
