# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-25 13:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0132_set_lms_module_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="is_lms_module_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
