# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-25 09:22


from django.db import migrations


def set_default_time_to_videos(apps, schema_editor):
    CourseItem = apps.get_model("trainings", "CourseItem")
    course_items = CourseItem.objects.all()
    for item in course_items:
        if not item.min_duration and item.videos.exists():
            item.min_duration = 10
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0133_auto_20191125_1316"),
    ]

    operations = [migrations.RunPython(set_default_time_to_videos, migrations.RunPython.noop)]
