# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-05 12:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0134_set_default_time_to_videos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseitem",
            name="min_duration",
            field=models.SmallIntegerField(
                blank=True,
                help_text="In seconds. Leave blank to populate with the default.",
                null=True,
            ),
        ),
    ]
