# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-08 15:25
from __future__ import unicode_literals

from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0137_auto_20191224_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[
                    apps.base.models.validate_us_phone_number,
                    apps.base.models.validate_us_phone_number,
                    apps.base.models.validate_us_phone_number,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="is_lms_module_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
