# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-03 03:51
from __future__ import unicode_literals

import datetime

from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0137_auto_20191224_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtasktype",
            name="required_within",
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="customtasktype",
            name="validity_period",
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[
                    apps.base.models.validate_us_phone_number,
                    apps.base.models.validate_us_phone_number,
                    apps.base.models.validate_us_phone_number,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="required_within",
            field=models.DurationField(
                blank=True,
                help_text="How long after the employees hire date/required after task type should this task type be due?",
            ),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="validity_period",
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
