# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-08 17:39
from __future__ import unicode_literals

from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0139_auto_20200103_0606"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="sponsored_access",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[
                    apps.base.models.validate_us_phone_number,
                    apps.base.models.validate_us_phone_number,
                    apps.base.models.validate_us_phone_number,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employeecourse",
            name="completed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employeecourse",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
