# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 05:22
from __future__ import unicode_literals

from django.db import migrations, models

import apps.base.models
import apps.trainings.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0141_auto_20200109_1811"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptedInFacility",
            fields=[],
            options={
                "verbose_name_plural": "Opted in Facilities",
                "proxy": True,
                "indexes": [],
            },
            bases=("trainings.facility",),
        ),
        migrations.AddField(
            model_name="facility",
            name="opted_in_sponsorship_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="is_lms_module_enabled",
            field=models.BooleanField(default=apps.trainings.models.have_sponsorships_started),
        ),
        migrations.AlterField(
            model_name="facility",
            name="sponsored_access",
            field=models.BooleanField(default=apps.trainings.models.have_sponsorships_started),
        ),
    ]
