# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0142_auto_20200110_0522"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OptedInFacility",
        ),
    ]
