# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0138_auto_20200108_1525"),
        ("trainings", "0143_delete_optedinfacility"),
    ]

    operations = []
