# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 22:13
from __future__ import unicode_literals

from django.db import migrations, models

import apps.base.models
import apps.trainings.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0144_merge_20200123_1902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="is_lms_module_enabled",
            field=models.BooleanField(default=apps.trainings.models.have_sponsorships_started),
        ),
    ]
