# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-25 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0145_auto_20200123_2213"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_global_requirement",
            field=models.BooleanField(default=False),
        ),
    ]
