# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-29 19:45
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0146_task_is_global_requirement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_global_requirement",
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="required_within",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                help_text="How long after the employees hire date/required after task type should this task type be due?",
            ),
        ),
    ]
