# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-01 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0147_auto_20200629_1945"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="address_county",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
