# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-20 21:23
from __future__ import unicode_literals

from django.db import migrations

from apps.base.geocoder import get_geolocation_point


def update_coords(apps, schema_editor):
    Facility = apps.get_model("trainings", "Facility")
    Sponsor = apps.get_model("subscriptions", "Sponsor")

    for facility in Facility.objects.all():
        # @property address
        s = ""
        s += facility.address_line1 + ", "
        if facility.address_line2:
            s += facility.address_line2 + ", "
        s += facility.address_city + ", "
        s += (facility.state or "") + " "
        s += facility.address_zipcode
        point = get_geolocation_point(s)

        if point is None:
            point = get_geolocation_point(facility.address_zipcode)
        if point is not None:
            Facility.objects.filter(id=facility.id).update(point=point)
    for sponsor in Sponsor.objects.all():
        point = get_geolocation_point(sponsor.zip_code)
        if point is not None:
            Sponsor.objects.filter(id=sponsor.id).update(point=point)


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0149_facility_point"),
        ("subscriptions", "0014_sponsor_point"),
    ]

    operations = [migrations.RunPython(update_coords)]
