# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-09-18 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0151_facility_tax_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="external_training_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="external_training_url",
            field=models.URLField(blank=True),
        ),
    ]
