# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-04 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0153_employeecourseitem_is_correct"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="multichoiceoption",
            options={"ordering": ["id"]},
        ),
    ]
