# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-05 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0154_auto_20210104_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecourseitem",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
