# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-03-03 00:15
from __future__ import unicode_literals

from django.db import migrations


def migrate_employees_position_administrator(apps, schema_editor):
    Position = apps.get_model("trainings", "Position")
    try:
        administrator_correct = Position.objects.filter(
            name="Administrator", facility__isnull=True
        ).get()
    except Position.DoesNotExist:
        return
    administrator_positions = Position.objects.filter(name="Administrator", facility__isnull=False)

    for administrator_wrong in administrator_positions:
        for employee in administrator_wrong.employee_set.all():
            employee.positions.add(administrator_correct)
            employee.positions.remove(administrator_wrong)
    administrator_positions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0155_employeecourseitem_completed_at"),
    ]

    operations = [
        migrations.RunPython(migrate_employees_position_administrator, migrations.RunPython.noop),
    ]
