# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-03-03 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0156_auto_20210303_0015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name="position",
            name="facility",
        ),
    ]
