# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-02-14 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0157_auto_20210303_1416"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_reactivated",
            field=models.BooleanField(default=False),
        ),
    ]
