# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-02-24 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0158_auto_20220210_1907"),
        ("trainings", "0158_employee_is_reactivated"),
    ]

    operations = []
