# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-03-24 13:34
from __future__ import unicode_literals

from django.db import migrations


def migrate_facility_questions(apps, schema_editor):
    State = apps.get_model("alfdirectory", "State")
    fl_state, _ = State.objects.get_or_create(state="FL")
    FacilityQuestion = apps.get_model("trainings", "FacilityQuestion")
    FacilityQuestionState = apps.get_model("trainings", "FacilityQuestionState")
    for facility_question in FacilityQuestion.objects.all():
        FacilityQuestionState.objects.update_or_create(state=fl_state, question=facility_question)


def migrate_facilities(apps, schema_editor):
    State = apps.get_model("alfdirectory", "State")
    fl_state, _ = State.objects.get_or_create(state="FL")
    Facility = apps.get_model("trainings", "Facility")
    Facility.objects.all().update(state_facility=fl_state)


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0160_auto_20220324_1333"),
    ]

    operations = [
        migrations.RunPython(migrate_facilities, migrations.RunPython.noop),
        migrations.RunPython(migrate_facility_questions, migrations.RunPython.noop),
    ]
