# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-05-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0161_trainings_state_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_optional",
            field=models.BooleanField(
                default=False,
                help_text="This flag is used for when an employee starts a course that is not part of his responsibilities",
            ),
        ),
    ]
