# Generated by Django 3.2.17 on 2023-02-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alfdirectory", "0004_alfdirectory_state_migration"),
        ("trainings", "0162_task_is_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseitemvideo",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="trainings.courseitem",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="is_staff_module_enabled",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="This just hides the module in the FE",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="state_facility",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainings_facilities",
                to="alfdirectory.state",
            ),
        ),
    ]
