# Generated by Django 3.2.17 on 2023-02-06 12:59

from django.db import migrations

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0163_auto_20230203_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="contact_fax",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                default="",
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="contact_phone",
            field=apps.base.models.UsPhoneNumberField(
                max_length=50, validators=[apps.base.models.validate_us_phone_number]
            ),
        ),
    ]
