# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-03-24 13:34
from __future__ import unicode_literals

from django.db import migrations


def migrate_alfdirectory_facilities(apps, schema_editor):
    State = apps.get_model("alfdirectory", "State")
    fl_state, _ = State.objects.get_or_create(state="FL")
    Facility = apps.get_model("alfdirectory", "Facility")
    Facility.objects.all().update(state=fl_state)


class Migration(migrations.Migration):

    dependencies = [
        ("alfdirectory", "0003_auto_20220324_1333"),
    ]

    operations = [
        migrations.RunPython(migrate_alfdirectory_facilities, migrations.RunPython.noop),
    ]
