# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0006_auto_20160520_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="section_2_b_other1_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="resident",
            name="section_2_b_other2_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="resident",
            name="section_2_b_other3_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="resident",
            name="section_2_b_other4_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
