# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 18:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0008_auto_20160524_1621"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resident",
            old_name="dose_pose_danger_comments",
            new_name="does_pose_danger_comments",
        ),
    ]
