# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 18:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0009_auto_20160527_1446"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="section_2_a_other_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Other name"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="section_2_a_other_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Independent"),
                    ("S*", "Needs Supervision *"),
                    ("A*", "Needs Assistance *"),
                ],
                max_length=2,
                verbose_name="Status",
            ),
        ),
    ]
