# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0010_auto_20160601_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="is_diet_low_sugar",
            field=models.BooleanField(default=False),
        ),
    ]
