# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:20


from django.db import migrations

from apps.base.models import UsPhoneNumberField


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0011_resident_is_diet_low_sugar"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="contact_1_mobile_phone",
            field=UsPhoneNumberField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="resident",
            name="contact_2_mobile_phone",
            field=UsPhoneNumberField(blank=True, max_length=20),
        ),
    ]
