# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0012_auto_20160613_1620"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resident",
            old_name="contact_1_phone",
            new_name="contact_1_home_phone",
        ),
        migrations.RenameField(
            model_name="resident",
            old_name="contact_2_phone",
            new_name="contact_2_home_phone",
        ),
    ]
