# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:35


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0013_auto_20160613_1626"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="residentrace",
            name="resident",
        ),
        migrations.DeleteModel(
            name="ResidentRace",
        ),
    ]
