# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0014_auto_20160613_1635"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("white", "White"),
                    ("black", "Black or African American"),
                    ("latino", "Hispanic/Latino"),
                    ("asian", "Asian"),
                    ("other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
