# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 11:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0015_resident_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="medicaid_number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
