# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 18:58


from django.db import migrations
from django.utils import timezone


def forward(apps, schema_editor):
    Resident = apps.get_model("residents", "Resident")
    Resident.objects.filter(date_of_discharge__lte=timezone.now().date()).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0016_resident_medicaid_number"),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
