# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 18:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0017_resident-is-active-set-from-discharge-date"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="signature_on_file",
            field=models.BooleanField(default=False),
        ),
    ]
