# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 21:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0018_resident_signature_on_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="is_dialysis_patient",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resident",
            name="is_under_hospice_care",
            field=models.BooleanField(default=False),
        ),
    ]
