# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-23 15:22


from django.db import migrations, models

import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0019_auto_20160912_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="bed",
            field=models.CharField(blank=True, max_length=255, verbose_name="Bed"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="date_of_admission",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Admission"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="date_of_discharge",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Discharge"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                max_length=255,
                verbose_name="Marital status",
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="personal_notes",
            field=models.TextField(blank=True, verbose_name="Personal notes"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("white", "White"),
                    ("black", "Black or African American"),
                    ("latino", "Hispanic/Latino"),
                    ("asian", "Asian"),
                    ("other", "Other"),
                ],
                max_length=255,
                verbose_name="Race",
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="religion",
            field=models.CharField(blank=True, max_length=255, verbose_name="Religion"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="room_number",
            field=models.CharField(blank=True, max_length=255, verbose_name="Room"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("m", "Male"), ("f", "Female"), ("other", "Other")],
                max_length=255,
                verbose_name="Sex",
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="ssn",
            field=localflavor.us.models.USSocialSecurityNumberField(
                blank=True, max_length=11, verbose_name="Social Security Number"
            ),
        ),
    ]
