# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 18:14


from django.db import migrations, models

from apps.base.models import UsPhoneNumberField


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0020_auto_20170223_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="case_worker_first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="resident",
            name="case_worker_last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="resident",
            name="case_worker_phone",
            field=UsPhoneNumberField(blank=True, max_length=20, verbose_name="Case Worker Phone #"),
        ),
        migrations.AddField(
            model_name="resident",
            name="dialysis_center",
            field=models.CharField(blank=True, max_length=255, verbose_name="Dialysis Center"),
        ),
        migrations.AddField(
            model_name="resident",
            name="dialysis_center_phone",
            field=UsPhoneNumberField(
                blank=True, max_length=20, verbose_name="Dialysis Center Phone #"
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="hospice_provider",
            field=models.CharField(blank=True, max_length=255, verbose_name="Hospice Provider"),
        ),
        migrations.AddField(
            model_name="resident",
            name="hospice_provider_phone",
            field=UsPhoneNumberField(
                blank=True, max_length=20, verbose_name="Hospice Provider Phone #"
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="examination_date",
            field=models.DateField(blank=True, null=True, verbose_name="1823 Exam Due"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="has_assistive_care_services",
            field=models.BooleanField(default=False, verbose_name="Status"),
        ),
    ]
