# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 16:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0021_auto_20170228_1814"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resident",
            name="is_able_to_administer_without_assistance",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="requires_help_taking_medication",
        ),
        migrations.AlterField(
            model_name="resident",
            name="long_term_care_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Long Term Care Plan #"
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="long_term_care_provider",
            field=models.CharField(blank=True, max_length=255, verbose_name="Long Term Care Plan"),
        ),
    ]
