# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 19:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0023_archived1823"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="is_able_to_administer_without_assistance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resident",
            name="requires_help_taking_medication",
            field=models.BooleanField(default=False),
        ),
    ]
