# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-01 17:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0025_auto_20170330_1426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="does_pose_danger",
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="resident",
            name="is_elopement_risk",
            field=models.NullBooleanField(default=False),
        ),
    ]
