# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-07 16:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0026_auto_20190101_1758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="does_pose_danger",
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name="resident",
            name="is_elopement_risk",
            field=models.NullBooleanField(),
        ),
    ]
