# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-15 16:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0027_auto_20190107_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="does_pose_danger",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="resident",
            name="is_elopement_risk",
            field=models.BooleanField(default=False),
        ),
    ]
