# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-19 19:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0028_auto_20190115_1633"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="long_term_care_provider_other",
            field=models.CharField(blank=True, max_length=255, verbose_name="Long Term Care Plan"),
        ),
    ]
