# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-20 12:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0029_resident_long_term_care_provider_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="npi",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
