# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-20 15:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0030_resident_npi"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="permanent_placement",
            field=models.BooleanField(default=False),
        ),
    ]
