# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-20 17:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0031_resident_permanent_placement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resident",
            old_name="reason_for_discharge",
            new_name="discharge_notes",
        ),
        migrations.AddField(
            model_name="resident",
            name="discharge_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
