# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-21 19:40


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0032_auto_20190620_1723"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidentBedHold",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_out", models.DateField()),
                ("date_in", models.DateField(blank=True, null=True)),
                ("sent_to", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bed_holds",
                        to="residents.Resident",
                    ),
                ),
            ],
        ),
    ]
