# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-26 18:59


import django.utils.timezone
from django.db import migrations, models

import model_utils.fields

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0033_residentbedhold"),
    ]

    operations = [
        migrations.CreateModel(
            name="IlsFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "generated_file",
                    models.FileField(
                        upload_to=apps.base.models.random_name_in("residents/ils_file")
                    ),
                ),
                ("uploaded", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="residentbedhold",
            unique_together=set([("resident", "date_out")]),
        ),
    ]
