# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-05 16:58


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0034_auto_20190626_1859"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resident",
            old_name="observering_wellbeing_comments",
            new_name="observing_wellbeing_comments",
        ),
    ]
