# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-12 20:23


from django.db import migrations


def reset_permanent_placement(apps, schema_editor):
    Resident = apps.get_model("residents.Resident")
    Resident.objects.all().update(permanent_placement=True)


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0036_auto_20190712_2022"),
    ]

    operations = [
        migrations.RunPython(reset_permanent_placement, migrations.RunPython.noop),
    ]
