# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-08-01 12:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0037_auto_20190712_2023"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resident",
            name="npi",
        ),
    ]
