# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "residents",
            "0039_provider_provideremail_providerfile_squashed_0040_auto_20200610_1821_squashed_0040_auto_20200611_1449",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="is_cha",
            field=models.BooleanField(default=False),
        ),
    ]
