# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-13 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0040_resident_is_cha"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="insurance_policy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="insurance_relationship",
            field=models.CharField(
                blank=True,
                choices=[("self", "Self"), ("spouse", "Spouse"), ("other", "Other")],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
