# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-15 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0041_auto_20210113_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="insured_first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Insured First Name"
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="insured_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="resident",
            name="insured_last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Insured Last Name"
            ),
        ),
    ]
