# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-10-08 18:55
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0042_auto_20210115_1236"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.base.models.random_name_in("residents/medications_files"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="resident",
            name="ambulation_comments",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="bathing_comments",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="dressing_comments",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="eating_comments",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="self_care_comments",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="toileting_comments",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="transferring_comments",
        ),
        migrations.AddField(
            model_name="medicationfile",
            name="resident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medication_files",
                to="residents.Resident",
            ),
        ),
    ]
