# Generated by Django 3.2.17 on 2023-02-06 12:59

from django.db import migrations

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0043_auto_20211008_1855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="case_worker_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=255,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="contact_1_home_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="contact_1_mobile_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="contact_2_home_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="contact_2_mobile_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="dialysis_center_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=255,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="examiner_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="hospice_provider_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=255,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="primary_doctor_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="psychiatric_doctor_phone",
            field=apps.base.models.UsPhoneNumberField(
                blank=True,
                max_length=50,
                validators=[apps.base.models.validate_us_phone_number],
            ),
        ),
    ]
