# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-03-14 17:25


import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PdfParameters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parameters", models.TextField()),
            ],
        ),
    ]
