# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 15:32


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingInterval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "interval_count",
                    models.PositiveIntegerField(
                        help_text="The number of intervals between each subscription billing."
                    ),
                ),
            ],
            options={
                "ordering": ["amount"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "capacity_limit",
                    models.PositiveIntegerField(blank=True, help_text="Inclusive", null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="billinginterval",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_intervals",
                to="subscriptions.Plan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="billinginterval",
            unique_together=set([("plan", "interval", "interval_count")]),
        ),
    ]
