# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 16:05


import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(
                default=datetime.datetime(2016, 6, 24, 16, 4, 58, 543675, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(
                default=datetime.datetime(2016, 6, 24, 16, 5, 1, 338777, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
