# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 18:33


from django.db import migrations, models

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_auto_20160624_1205"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="trial_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("pending_cancel", "Pending Cancellation"),
                ],
                default="active",
                max_length=50,
            ),
        ),
    ]
