# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-04 21:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_auto_20160705_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="module",
            field=models.CharField(
                choices=[("resident", "Resident"), ("staff", "Staff")],
                default="resident",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
