# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-14 23:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_facilitypaymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="module",
            field=models.CharField(
                choices=[
                    ("resident", "Resident"),
                    ("staff", "Staff"),
                    ("trainings", "Trainings"),
                ],
                max_length=50,
            ),
        ),
    ]
