# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_sponsorship_sponsorshipfacility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorship",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Sponsor Name"),
        ),
    ]
