# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-16 03:49
from __future__ import unicode_literals

from django.db import migrations

import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_auto_20200114_0043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("trialing", "Trialing"),
                    ("trial_expired", "Trial Expired"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("pending_cancel", "Pending Cancellation"),
                ],
                default="active",
                max_length=50,
            ),
        ),
    ]
