# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-15 18:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_auto_20200114_0043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorship",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsorhips",
                to="subscriptions.Sponsor",
            ),
        ),
    ]
