# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-16 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0012_auto_20200116_0349"),
        ("subscriptions", "0012_auto_20200115_1838"),
    ]

    operations = []
