# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2022-03-23 20:45
from __future__ import unicode_literals

from django.db import migrations


def migrate_sponsors(apps, schema_editor):
    State = apps.get_model("alfdirectory", "State")
    fl_state, _ = State.objects.get_or_create(state="FL")
    Sponsor = apps.get_model("subscriptions", "Sponsor")
    SponsorState = apps.get_model("trainings", "SponsorState")
    for sponsor in Sponsor.objects.all():
        SponsorState.objects.update_or_create(sponsor=sponsor, state=fl_state)


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0015_sponsor_state"),
    ]

    operations = [
        migrations.RunPython(migrate_sponsors, migrations.RunPython.noop),
    ]
