# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 00:44


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("account.updated", "account.updated"),
                            (
                                "account.application.deauthorized",
                                "account.application.deauthorized",
                            ),
                            (
                                "account.external_account.created",
                                "account.external_account.created",
                            ),
                            (
                                "account.external_account.deleted",
                                "account.external_account.deleted",
                            ),
                            (
                                "account.external_account.updated",
                                "account.external_account.updated",
                            ),
                            ("application_fee.created", "application_fee.created"),
                            ("application_fee.refunded", "application_fee.refunded"),
                            (
                                "application_fee.refund.updated",
                                "application_fee.refund.updated",
                            ),
                            ("balance.available", "balance.available"),
                            ("bitcoin.receiver.created", "bitcoin.receiver.created"),
                            ("bitcoin.receiver.filled", "bitcoin.receiver.filled"),
                            ("bitcoin.receiver.updated", "bitcoin.receiver.updated"),
                            (
                                "bitcoin.receiver.transaction.created",
                                "bitcoin.receiver.transaction.created",
                            ),
                            ("charge.captured", "charge.captured"),
                            ("charge.failed", "charge.failed"),
                            ("charge.refunded", "charge.refunded"),
                            ("charge.succeeded", "charge.succeeded"),
                            ("charge.updated", "charge.updated"),
                            ("charge.dispute.closed", "charge.dispute.closed"),
                            ("charge.dispute.created", "charge.dispute.created"),
                            (
                                "charge.dispute.funds_reinstated",
                                "charge.dispute.funds_reinstated",
                            ),
                            (
                                "charge.dispute.funds_withdrawn",
                                "charge.dispute.funds_withdrawn",
                            ),
                            ("charge.dispute.updated", "charge.dispute.updated"),
                            ("coupon.created", "coupon.created"),
                            ("coupon.deleted", "coupon.deleted"),
                            ("coupon.updated", "coupon.updated"),
                            ("customer.created", "customer.created"),
                            ("customer.deleted", "customer.deleted"),
                            ("customer.updated", "customer.updated"),
                            ("customer.discount.created", "customer.discount.created"),
                            ("customer.discount.deleted", "customer.discount.deleted"),
                            ("customer.discount.updated", "customer.discount.updated"),
                            ("customer.source.created", "customer.source.created"),
                            ("customer.source.deleted", "customer.source.deleted"),
                            ("customer.source.updated", "customer.source.updated"),
                            (
                                "customer.subscription.created",
                                "customer.subscription.created",
                            ),
                            (
                                "customer.subscription.deleted",
                                "customer.subscription.deleted",
                            ),
                            (
                                "customer.subscription.trial_will_end",
                                "customer.subscription.trial_will_end",
                            ),
                            (
                                "customer.subscription.updated",
                                "customer.subscription.updated",
                            ),
                            ("invoice.created", "invoice.created"),
                            ("invoice.payment_failed", "invoice.payment_failed"),
                            ("invoice.payment_succeeded", "invoice.payment_succeeded"),
                            ("invoice.updated", "invoice.updated"),
                            ("invoiceitem.created", "invoiceitem.created"),
                            ("invoiceitem.deleted", "invoiceitem.deleted"),
                            ("invoiceitem.updated", "invoiceitem.updated"),
                            ("order.created", "order.created"),
                            ("order.payment_failed", "order.payment_failed"),
                            ("order.payment_succeeded", "order.payment_succeeded"),
                            ("order.updated", "order.updated"),
                            ("plan.created", "plan.created"),
                            ("plan.deleted", "plan.deleted"),
                            ("plan.updated", "plan.updated"),
                            ("product.created", "product.created"),
                            ("product.deleted", "product.deleted"),
                            ("product.updated", "product.updated"),
                            ("recipient.created", "recipient.created"),
                            ("recipient.deleted", "recipient.deleted"),
                            ("recipient.updated", "recipient.updated"),
                            ("sku.created", "sku.created"),
                            ("sku.deleted", "sku.deleted"),
                            ("sku.updated", "sku.updated"),
                            ("transfer.created", "transfer.created"),
                            ("transfer.failed", "transfer.failed"),
                            ("transfer.paid", "transfer.paid"),
                            ("transfer.reversed", "transfer.reversed"),
                            ("transfer.updated", "transfer.updated"),
                            ("ping", "ping"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created", models.DateTimeField()),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                ("pending_webhooks", models.PositiveIntegerField()),
                ("request", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
