# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 16:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examiners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="residentaccess",
            options={"verbose_name_plural": "resident accesses"},
        ),
    ]
