# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-05 20:56


import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0025_auto_20170330_1426"),
        ("examiners", "0002_auto_20170310_1636"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExaminationRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[("sent", "sent"), ("examined", "examined")],
                        default="sent",
                        max_length=50,
                    ),
                ),
                (
                    "examiner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examination_requests",
                        to="examiners.Examiner",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examination_requests",
                        to="residents.Resident",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "examination requests",
            },
        ),
    ]
