# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-04 21:15


from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actstream", "0002_remove_action_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[],
            options={
                "proxy": True,
                "verbose_name_plural": "activities",
            },
            bases=("actstream.action",),
        ),
    ]
