# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 15:59


from django.db import migrations, models

import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TutorialVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, editable=False)),
                ("title", models.CharField(max_length=100)),
                ("url", embed_video.fields.EmbedVideoField()),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
